//! `npu config schema <KIND>`: the JSON Schema (draft-07) of one
//! configuration format, derived from the raw deserialize structs.
//!
//! The schemas are generated by the unit test below (`schemars` is a
//! dev-dependency) and committed under `schemas/`; the binary only embeds
//! them. The test fails when a struct and its committed schema disagree, and
//! rewrites the files when `NPU_UPDATE_SCHEMAS` is set.
//!
//! A schema is structural: it knows the keys, their types and the few
//! literal values `validate_backend` accepts, not the rules that tie keys
//! together (`values` only with `type = "enum"`, a model's backend must
//! exist). `npu config check` stays authoritative.

/// The formats `config schema` knows, in the order `--help` lists them.
pub const SCHEMA_KINDS: &[&str] = &["backend", "model", "command", "test"];

/// The committed schema of `kind`, `None` for a kind not in
/// [`SCHEMA_KINDS`] (which `clap` already refuses).
#[must_use]
pub fn config_schema(kind: &str) -> Option<&'static str> {
    match kind {
        "backend" => Some(include_str!("../../schemas/backend.json")),
        "model" => Some(include_str!("../../schemas/model.json")),
        "command" => Some(include_str!("../../schemas/command.json")),
        "test" => Some(include_str!("../../schemas/test.json")),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::panic)]

    use super::{SCHEMA_KINDS, config_schema};

    /// Generates the schema of `T`, titled for an editor's hover.
    fn generate<T: schemars::JsonSchema>(title: &str) -> String {
        let schema = schemars::generate::SchemaSettings::draft07()
            .into_generator()
            .into_root_schema_for::<T>();
        let mut value = serde_json::to_value(schema).expect("a schema serializes");
        tidy(&mut value);
        let root = value.as_object_mut().expect("a root schema is an object");
        root.insert("title".to_string(), title.into());
        root.insert(
            "description".to_string(),
            "Structural schema: `npu config check` is authoritative.".into(),
        );
        let mut text = serde_json::to_string_pretty(&value).expect("a schema serializes");
        text.push('\n');
        text
    }

    /// Rustdoc comments are dropped: they document the code, not the
    /// format, and would make every comment edit a schema change. `null` is
    /// dropped too: TOML has none, an `Option` is left out by omitting the
    /// key.
    fn tidy(value: &mut serde_json::Value) {
        use serde_json::Value;
        match value {
            Value::Object(map) => {
                map.remove("description");
                if map.get("default") == Some(&Value::Null) {
                    map.remove("default");
                }
                if let Some(Value::Array(types)) = map.get_mut("type") {
                    types.retain(|kind| kind != "null");
                    if let [only] = types.as_slice() {
                        let only = only.clone();
                        map.insert("type".to_string(), only);
                    }
                }
                if let Some(Value::Array(branches)) = map.get("anyOf")
                    && let [kept, null] = branches.as_slice()
                    && *null == serde_json::json!({"type": "null"})
                {
                    let kept = kept.clone();
                    map.remove("anyOf");
                    // Draft-07 ignores a `$ref`'s siblings (`deprecated`).
                    if kept.get("$ref").is_some() && !map.is_empty() {
                        map.insert("allOf".to_string(), Value::Array(vec![kept]));
                    } else if let Value::Object(kept) = kept {
                        map.extend(kept);
                    }
                }
                map.values_mut().for_each(tidy);
            }
            Value::Array(items) => items.iter_mut().for_each(tidy),
            _ => {}
        }
    }

    fn generated(kind: &str) -> String {
        match kind {
            "backend" => generate::<crate::config::Backend>("npu backend file"),
            "model" => generate::<crate::config::Model>("npu model file"),
            "command" => generate::<crate::command::Frontmatter>("npu command frontmatter"),
            "test" => generate::<super::super::test::RawCase>("npu test case file"),
            other => panic!("no generator for schema kind {other:?}"),
        }
    }

    /// Validates a TOML document against a committed schema, as an editor
    /// would.
    fn accepts(kind: &str, toml_source: &str) -> bool {
        let schema: serde_json::Value =
            serde_json::from_str(config_schema(kind).expect("a known kind")).expect("valid JSON");
        let document: toml::Value = toml::from_str(toml_source).expect("valid TOML");
        let document = serde_json::to_value(document).expect("TOML maps to JSON");
        jsonschema::is_valid(&schema, &document)
    }

    #[test]
    fn the_schemas_accept_a_valid_file_and_reject_an_unknown_key() {
        let cases = [
            (
                "backend",
                "id = \"b\"\nbase_url = \"http://localhost:8000\"\ntype = \"openai-compatible\"\n\
                 port = \"auto\"\n[operations.chat]\nmethod = \"post\"\npath = \"/v1/chat\"\n\
                 [runtime]\ntype = \"process\"\ncommand = \"llama-server\"\n",
            ),
            (
                "model",
                "id = \"m\"\nbackend = \"b\"\noperation = \"chat\"\nmodel = \"qwen\"\n\
                 [generation]\ntemperature = 0.0\n[generation.extra]\nkeep_alive = 5\n",
            ),
            (
                "command",
                "model = \"m\"\n[args.language]\ntype = \"enum\"\nvalues = [\"fr\"]\n\
                 [output]\nformat = \"json\"\n",
            ),
            (
                "test",
                "input = { file = \"a.txt\" }\n[expect]\n\"/x\" = { min = 0.8 }\n",
            ),
        ];
        for (kind, source) in cases {
            assert!(accepts(kind, source), "{kind}: a valid file must validate");
            assert!(
                !accepts(kind, &format!("typo_key = 1\n{source}")),
                "{kind}: an unknown key must be rejected"
            );
        }
        assert!(!accepts(
            "backend",
            "id = \"b\"\nbase_url = \"u\"\ntype = \"ollama\"\noperations = {}\n"
        ));
    }

    #[test]
    fn committed_schemas_match_the_structs() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("schemas");
        let update = std::env::var_os("NPU_UPDATE_SCHEMAS").is_some();
        for kind in SCHEMA_KINDS {
            let fresh = generated(kind);
            let path = dir.join(format!("{kind}.json"));
            if update {
                std::fs::write(&path, &fresh).expect("schemas/ is writable");
            } else {
                assert_eq!(
                    config_schema(kind),
                    Some(fresh.as_str()),
                    "{} is stale: rerun the tests with NPU_UPDATE_SCHEMAS=1",
                    path.display()
                );
            }
        }
    }
}
