//! `npu backend tune`: sizes the static context of every NPU-compiled model
//! from the model's own characteristics and the host's memory.
//!
//! An `OpenVINO` NPU graph is compiled for a STATIC context: `MAX_PROMPT_LEN`
//! tokens of prompt plus `MIN_RESPONSE_LEN` tokens of answer, both read from
//! the root of `plugin_config` in the export's `graph.pbtxt`. A longer prompt
//! is refused, a longer answer is cut. This module picks both values, and the
//! matching `[generation].max_tokens` of the model file and of its fallback,
//! from:
//!
//! - the model: `max_position_embeddings` and the per-token cost read from
//!   its Hugging Face `config.json`;
//! - the host: `--max-memory` percent of the total RAM, minus the weights of
//!   the `--max-models` heaviest NPU models, split evenly between them so they
//!   can all run at once.
//!
//! GPU twins are outside the budget: their context is dynamic, so there is
//! nothing to size, but on unified memory a served twin adds its own KV
//! cache on top of it.

use std::fmt::Write as _;
use std::path::Path;

use crate::vendor::huggingface::shape_of;
use crate::vendor::openvino::graph::{Device, Planned, plan_graph};

/// Sets `max_tokens` inside the `[generation]` table of a model file, adding
/// the key or the table when absent, and leaving every other line — comments
/// included — untouched. The result is re-parsed: any layout this line edit
/// does not understand (a dotted key, an inline table) is refused naming the
/// file, never written.
fn set_max_tokens(text: &str, max_tokens: u64, source: &Path) -> crate::Result<String> {
    let line = format!("max_tokens = {max_tokens}");
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let header = lines
        .iter()
        .position(|l| l.trim_start().starts_with("[generation]"));
    match header {
        Some(header) => {
            let table_end = lines[header + 1..]
                .iter()
                .position(|l| l.trim_start().starts_with('['))
                .map_or(lines.len(), |i| header + 1 + i);
            let existing = (header + 1..table_end).find(|&i| {
                lines[i]
                    .trim_start()
                    .strip_prefix("max_tokens")
                    .is_some_and(|rest| rest.trim_start().starts_with('='))
            });
            match existing {
                Some(i) => lines[i] = line,
                None => lines.insert(header + 1, line),
            }
        }
        None => lines.extend([String::new(), "[generation]".into(), line]),
    }
    let edited = lines.join("\n") + "\n";

    let parsed: crate::config::Model = toml::from_str(&edited).map_err(|e| {
        crate::Error::Config(crate::error::ConfigError::in_file(
            source,
            None::<String>,
            format!("cannot set [generation].max_tokens in this layout: {e}"),
        ))
    })?;
    if parsed.generation.max_tokens != Some(u32::try_from(max_tokens).unwrap_or(u32::MAX)) {
        return Err(crate::Error::Config(crate::error::ConfigError::in_file(
            source,
            None::<String>,
            "cannot set [generation].max_tokens in this layout",
        )));
    }
    Ok(edited)
}

/// Replaces `path` rather than rewriting it: a `graph.pbtxt` generated by a
/// container running as another user cannot be opened for writing, but can
/// be replaced when its directory is ours. A crash mid-way never leaves a
/// half-written file either.
fn replace_file(path: &Path, text: &str) -> crate::Result<()> {
    let mut staging = path.as_os_str().to_owned();
    staging.push(".npu-tune.tmp");
    let with_path =
        |e: std::io::Error| std::io::Error::new(e.kind(), format!("{}: {e}", path.display()));
    std::fs::write(&staging, text).map_err(with_path)?;
    std::fs::rename(&staging, path).map_err(with_path)?;
    Ok(())
}

fn read_export(path: &Path) -> crate::Result<String> {
    std::fs::read_to_string(path).map_err(|e| {
        crate::Error::Config(crate::error::ConfigError::in_file(
            path,
            None::<String>,
            e.to_string(),
        ))
    })
}

/// `12_345_678_901` -> `"12.3"`: gigabytes with one decimal, in integers.
fn gb(bytes: u64) -> String {
    format!("{}.{}", bytes / 1_000_000_000, bytes / 100_000_000 % 10)
}

/// What the caller constrains: which devices are tuned, how many of their
/// models run at once (`None`: all of them), which share of the total RAM
/// they get together, in percent, and whether GPU KV caches are `u8`.
#[derive(Debug, Clone, Copy)]
pub struct Limits {
    pub npu: bool,
    pub gpu: bool,
    pub max_models: Option<usize>,
    pub max_memory_percent: u64,
    pub kv_u8: bool,
}

/// Plans every model whose export under `models_dir` is compiled for a
/// device in `limits`, writes it unless `dry_run`, and returns the plan —
/// this command's result. Every new content is computed before anything is
/// written, so a malformed file aborts the whole run instead of half of it.
///
/// # Errors
///
/// - `Error::Config` when no model has an export for those devices, or when
///   an export or a model file is missing or malformed — naming the file;
/// - `Error::Io` when a file cannot be replaced.
pub fn tune(
    config: &crate::config::Config,
    models_dir: &Path,
    total_ram: u64,
    limits: Limits,
    dry_run: bool,
    logger: crate::log::Logger,
) -> crate::Result<String> {
    let mut ids: Vec<&String> = config.models.keys().collect();
    ids.sort_unstable();

    let mut planned = Vec::new();
    for id in ids {
        let export = models_dir.join(&config.models[id].model);
        let graph = export.join("graph.pbtxt");
        let device = std::fs::read_to_string(&graph)
            .ok()
            .and_then(|g| Device::of(&g))
            .filter(|d| match d {
                Device::Npu => limits.npu,
                Device::Gpu => limits.gpu,
            });
        let Some(device) = device else {
            continue;
        };
        let config_json = export.join("config.json");
        let json: serde_json::Value =
            serde_json::from_str(&read_export(&config_json)?).map_err(|e| {
                crate::Error::Config(crate::error::ConfigError::in_file(
                    &config_json,
                    None::<String>,
                    e.to_string(),
                ))
            })?;
        let weights_file = export.join("openvino_model.bin");
        let weights = std::fs::metadata(&weights_file)
            .map_err(|e| {
                crate::Error::Config(crate::error::ConfigError::in_file(
                    &weights_file,
                    None::<String>,
                    e.to_string(),
                ))
            })?
            .len();
        planned.push(Planned {
            id: id.clone(),
            device,
            shape: shape_of(&json, &config_json)?,
            weights,
            graph,
        });
    }
    let devices = match (limits.npu, limits.gpu) {
        (true, false) => "NPU",
        (false, true) => "GPU",
        _ => "NPU or GPU",
    };
    if planned.is_empty() {
        return Err(crate::Error::config(format!(
            "no configured model has an {devices} export under {}",
            models_dir.display()
        )));
    }
    if limits.kv_u8 && !limits.gpu {
        logger.warn("--kv-u8 only applies to GPU models: ignored with --npu alone");
    }

    let at_once = limits
        .max_models
        .unwrap_or(planned.len())
        .clamp(1, planned.len());
    let mut heaviest: Vec<u64> = planned.iter().map(|p| p.weights).collect();
    heaviest.sort_unstable_by(|a, b| b.cmp(a));
    let weights: u64 = heaviest.iter().take(at_once).sum();
    let granted = total_ram / 100 * limits.max_memory_percent;
    let budget = granted.saturating_sub(weights) / at_once as u64;

    let mut report = format!(
        "RAM {} GB x {}% - weights {} GB = {} GB per model ({at_once} of {} {devices} models at once)\n\n\
         {:32} {:6} {:>9} {:>9} {:>7} {:>7} {:>11}\n",
        gb(total_ram),
        limits.max_memory_percent,
        gb(weights),
        gb(budget),
        planned.len(),
        "model",
        "device",
        "model max",
        "KV/token",
        "prompt",
        "answer",
        "est. memory",
    );
    let mut writes = Vec::new();
    for p in &planned {
        let graph_text = std::fs::read_to_string(&p.graph)?;
        let (text, prompt, response, memory) = plan_graph(p, &graph_text, budget, limits.kv_u8)?;
        if memory > budget {
            logger.warn(&format!(
                "model \"{}\": even the smallest context ({} tokens) exceeds its share of {} GB",
                p.id,
                prompt + response,
                gb(budget)
            ));
        }
        let _ = writeln!(
            report,
            "{:32} {:6} {:>9} {:>7}KB {prompt:>7} {response:>7} {:>9}GB",
            p.id,
            p.device.label(),
            p.shape.max_context,
            p.shape.kv_per_token / 1024,
            gb(memory + p.weights),
        );
        writes.push((p.graph.clone(), text));
        let file = &config.models[&p.id].source;
        let model_text = std::fs::read_to_string(file)?;
        writes.push((file.clone(), set_max_tokens(&model_text, response, file)?));
    }

    if dry_run {
        append_calibration(&mut report);
    } else {
        for (path, text) in &writes {
            replace_file(path, text)?;
        }
        logger.info(
            "applied the plan to each graph.pbtxt and the max_tokens of each model: \
             the next `npu backend serve` recompiles the graph",
        );
    }
    Ok(report.trim_end().to_string())
}

/// Additive, stdout only: the constants behind the NPU column of `report`,
/// so a user on other hardware can see why the numbers are what they are
/// (see `vendor::openvino::graph`'s `## Calibration` section).
fn append_calibration(report: &mut String) {
    let _ = write!(
        report,
        "\n\ncalibration (vendor::openvino::graph): activation_tenths={} \
         activation_tenths_long={} long_context={} step={}",
        crate::vendor::openvino::graph::ACTIVATION_TENTHS,
        crate::vendor::openvino::graph::ACTIVATION_TENTHS_LONG,
        crate::vendor::openvino::graph::LONG_CONTEXT,
        crate::vendor::openvino::graph::STEP,
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn path() -> &'static Path {
        Path::new("models/x.toml")
    }

    const MODEL: &str =
        "# comment\nid = \"x\"\nbackend = \"b\"\noperation = \"chat\"\nmodel = \"m\"\n";

    fn max_tokens_of(text: &str) -> Option<u32> {
        toml::from_str::<crate::config::Model>(text)
            .ok()
            .and_then(|m| m.generation.max_tokens)
    }

    #[test]
    fn max_tokens_is_replaced_added_or_given_a_table() {
        let replaced = set_max_tokens(
            &format!("{MODEL}[generation]\nmax_tokens = 1\n"),
            99,
            path(),
        );
        assert_eq!(replaced.as_deref().map(max_tokens_of).ok(), Some(Some(99)));
        let added = set_max_tokens(
            &format!("{MODEL}[generation]\ntemperature = 0.0\n"),
            7,
            path(),
        );
        assert_eq!(added.as_deref().map(max_tokens_of).ok(), Some(Some(7)));
        let table = set_max_tokens(MODEL, 5, path()).unwrap_or_default();
        assert_eq!(max_tokens_of(&table), Some(5));
        assert!(table.starts_with("# comment\n"));
    }

    #[test]
    fn a_layout_the_line_edit_does_not_understand_is_refused() {
        let inline = format!("{MODEL}generation = {{ max_tokens = 1 }}\n");
        assert!(matches!(
            set_max_tokens(&inline, 9, path()),
            Err(crate::Error::Config(_))
        ));
    }

    #[test]
    fn gigabytes_keep_one_truncated_decimal() {
        assert_eq!(gb(65_500_000_000), "65.5");
        assert_eq!(gb(7_079_999_999), "7.0");
    }
}
